### ISSUE TITLE
Migration issue with 0.12.1 and Django 1.11

### ISSUE THREAD

**Issue by guozhengli** [rbarrois/django_xworkflows#30]
Hello, very thank you for your provide the django workflow tools, but using a tool when you encounter a problem, please answer. Thanks
The question is:

```python
class OnlinePublishFlow(xwf_models.WorkflowEnabled, models.Model):

    online_state = xwf_models.StateField(OnlinePublishWorkflow)
    publish =  models.OneToOneField(APublish, verbose_name=u'test')
```

Execute python manage. Py makemigrations errors as follows：

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 177, in handle
    migration_name=self.migration_name,
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 47, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 198, in _detect_changes
    self._optimize_migrations()
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 362, in _optimize_migrations
    migration.operations = MigrationOptimizer().optimize(migration.operations, app_label=app_label)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/optimizer.py", line 38, in optimize
    result = self.optimize_inner(operations, app_label)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/optimizer.py", line 53, in optimize_inner
    result = operation.reduce(other, in_between, app_label)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 229, in reduce
    return super(CreateModel, self).reduce(operation, in_between, app_label=app_label)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 40, in reduce
    not operation.references_model(self.name, app_label)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 123, in references_model
    model_app_label, model_name = self.model_to_key(model)
  File "/root/workspaces/reapal-cmdb/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 137, in model_to_key
    return model._meta.app_label, model._meta.object_name
AttributeError: type object 'WorkflowEnabled' has no attribute '_meta'
```

Looking forward to your answer thank you

**Comment by hsmett** [comment]
Hello @rbarrois !
@mrjmad and I have the same issue with Django 1.11.9
Any thoughts?
Thank you very much

**Comment by rbarrois** [comment]
Hi!

Django 1.11 is officially supported, and should be thoroughly tested.

Regarding the current issue, I've increased the testing level (as seen in the [related branch](https://github.com/rbarrois/django_xworkflows/tree/repro/issue-30)), but couldn't reproduce the problem.

Could you provide more information - what kind of code change is causing the issue, Django / Python versions, etc.?

**Comment by hsmett** [comment]
Hello @rbarrois 
I've created a repo, containing the minimal required code to highlight the issue.
[https://github.com/hsmett/django_xworkflows_issue](https://github.com/hsmett/django_xworkflows_issue)
Any required info can be found in the README file, but let me know if you need anything.
Thank you very much for your time.

**Comment by rbarrois** [comment]
@hsmett thanks for the details! The issue only arises when we add, **in the same migration**, a ``WorkflowEnabled`` model and a ``ForeignKey`` pointing to it.

This should be fixed now; could you try with the latest master and report any issue you find?
If all is fine, I'll release the version :)

**Comment by hsmett** [comment]
Problem solved! Thank you very much :D
